version: 2.1

orbs:
  haskell: haskell-works/haskell-build@1.4.0
  github: haskell-works/github-release@1.2.1

executors:
  build-executor:
    docker:
      - image: quay.io/haskell_works/ghc-8.4.4
      - image: confluentinc/cp-zookeeper:5.1.0
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181

      - image: confluentinc/cp-kafka:5.1.0
        environment:
          KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

commands:
  build-librdkafka:
    description: Build librdkafka
    steps:
      - restore_cache:
          key: cache--{{ .Environment.CACHE_VERSION }}--librdkafka--{{ checksum "scripts/build-librdkafka" }}
      - run:
          name: Build librdkafka
          command: ./scripts/build-librdkafka
      - save_cache:
          key: cache--{{ .Environment.CACHE_VERSION }}--librdkafka--{{ checksum "scripts/build-librdkafka" }}
          paths: ~/project/.librdkafka

workflows:
  build-app-pipelines:
    jobs:
      - haskell/build:
          name: GHC 8.4.4
          executor: build-executor
          before-build: [build-librdkafka]

      - haskell/build:
          name: GHC 8.6.3
          executor: build-executor
          before-build: [build-librdkafka]

      - github/release-cabal:
          name: GitHub Release
          requires: [GHC 8.4.4, GHC 8.6.3]
          checkout: true
          filters:
            branches:
              only: master
